TFT_FILES = BMPFile gciWidget Hazard Liberation OCR_A Open24Display Raw565File TFT Widgets
TFT_ZIP = TFT-Complete.zip

ZIPS = ${TFT_ZIP}

${TFT_ZIP}: ${TFT_FILES}
	zip -r ${TFT_ZIP} ${TFT_FILES} -x *.git*
